stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image:
    name: node:latest
  script:
    - npm install
    - npm run build

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - echo "All tests have been passed"

lint-test-job:
  stage: test
  image:
    name: node:latest
  script:
    - npm install
    - npm run lint

deploy-job:
  stage: deploy
  image:
    name: debian:latest
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SERVER_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  script:
    - ./ci/deploy.sh
